fields:
  - cpus:
    name: cpus
    key: 10062
    description: x
  - ram:
    name: ram
    key: 10063
    description:
  - appname:
    name: appname
    key: 10060
    description:
  - image:
    name: image
    key: 10061
    description:
  - env:
    name: env
    key: 10064
    description: 
  - role:
    name: role
    key: 10065
    description: 
  - nodes:
    name: nodes
    key: 10066
    description: 
  - network:
    name: network
    key: 10067
    description: 
  - disk:
    name: disk
    key: 10068
    description: 
---