fields:
  - cpus:
    name: cpus
    field_id: 10062
    description: x
  - ram:
    name: ram
    field_id: 10063
    description:
  - appname:
    name: appname
    field_id: 10060
    description:
  - image:
    name: image
    field_id: 10061
    description:
  - env:
    name: env
    field_id: 10064
    description: 
  - role:
    name: role
    field_id: 10065
    description: 
  - nodes:
    name: nodes
    field_id: 10066
    description: 
  - network:
    name: network
    field_id: 10067
    description: 
  - disk:
    name: disk
    field_id: 10068
    description: 
---